apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyI1Mi4xNDkuMTA0LjU1OjUwMDAiOnsidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiYWRtaW4xMjMiLCJlbWFpbCI6ImRlYmp5b3RpLmRhc3NAZ21haWwuY29tIiwiYXV0aCI6IllXUnRhVzQ2WVdSdGFXNHhNak09In19fQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: registrykey-332488
type: kubernetes.io/dockerconfigjson
